### PR TITLE
[BUGFIX] don't invoke prefetch during teardown

### PR DESCRIPTION
**Pull request by runspired**

### CODE REVIEW

**Review by stefanpenner — APPROVED** [review]

**Comment by rwjblue** [comment]
CI is broken due to needing `--no-sandbox` to the Chrome config settings in `testem.js`

**Comment by rwjblue** [comment]
Submitted https://github.com/nickiaconis/ember-prefetch/pull/99 to fix CI

**Comment by rwjblue** [comment]
restarted CI after #99 landed, if we still see the same failures RE: setuid this will need a rebase

**Review by rwjblue — APPROVED** [review]

**Comment by stefanpenner** [comment]
rebase against #99 may fix

**Comment by rwjblue** [comment]
rebasing in https://github.com/nickiaconis/ember-prefetch/pull/100

**Pull request closed without merging**
