### PR TITLE
Remove deprecated Ember.copy

### PR DESCRIPTION
**Pull request by nlfurniss**
Since this isn't using `Ember.copy` to copy deeply, this should be fine.

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
I haven’t dug deeply, but I believe CI is failing here due to Ember 2.4 not having Ember.assign. There is a polyfill you can add as a dep though...

**Comment by nlfurniss** [comment]
@rwjblue how do you feel about dropping 2.4 and bumping the major? It's so old at this point that I think that'd be better than adding more code

**Comment by rwjblue** [comment]
Yep, seems totally fine to me also. I’d go all the way to 2.18 as minimum I think...

**Comment by nlfurniss** [comment]
Not sure if I made a mistake or this is just a CI failure...

**Comment by rwjblue** [comment]
`ember-lts-2.18` isn't in config/ember-try.js (thats what the error is saying). When you add it, could you also delete 2.4/2.8?

**Comment by nlfurniss** [comment]
Ok we in business!

**Review by nickiaconis — APPROVED** [review]
Thanks for the upkeep effort @nlfurniss! 😄

@rwjblue, would you take the reins on ushering this in? I've been away from the project for so long now, I hardly feel in the right to do so. Do you have all the permissions you need?

**Comment by rwjblue** [comment]
I just merged #125 which handled the ember-try things here, would you mind rebasing (which will drop out the `.travis.yml` and `config/ember-try.js` changes)?

**Comment by nlfurniss** [comment]
Rebased and ready to go :-)

**Comment by rwjblue** [comment]
Thank you @nlfurniss!

**Comment by rwjblue** [comment]
ember-prefetch 3.0.1 published 🎉

**Pull request merged**
