### PR TITLE
Add prettier to linting configuration

### PR DESCRIPTION
**Pull request by jackson-dean**
- Remove ember-cli-eslint dependency and replace it with direct
dependency on eslint and required plugins.

NOTE: disabling no-new-mixins for since prefetch currently relies on
a mixin.

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

**Review by rwjblue — COMMENTED** [review]
@jackson-dean - You also need to add `yarn eslint .` to `.travis.yml` or linting isn't enforced in CI.

**Comment by jackson-dean** [comment]
ahh, i thought this is covered by `yarn lint:js`? which just wraps `yarn eslint .`

**Comment by jackson-dean** [comment]
and which is already in travis config. I can change it though, just want to make sure its not running twice @rwjblue 

from the logs for the last CI run for this PR https://travis-ci.org/nickiaconis/ember-prefetch/jobs/589146899#L502

**Comment by rwjblue** [comment]
Hmm, you are definitely correct. I guess I assumed that this wasn't running in CI because I assumed there would be TONS of changes to apply prettier to the codebase.

But I think that whats happening here is that you've added the packages for prettier, but not added it to the eslint config. Is that intentional?

**Comment by jackson-dean** [comment]
Ahh it was just an oversight. I looked at a PR in ember engines that was
bumping linting packages and just grabbed what looked relevant. Didn’t
really think too much about prettier 😅
However our time line for the project that depends on these prefetch
changes just got delayed so not a huge rush for us on this stuff. I can
look at adding prettier configs here if you would like to have it set up
and then circle back to the lazy route thing.

**Comment by rwjblue** [comment]
> I can look at adding prettier configs here if you would like to have it set up

ya, definitely love to use prettier here...

**Comment by jackson-dean** [comment]
Cool I will work tomorrow on it early next week

**Comment by jackson-dean** [comment]
I added a separate commit for running prettier. Can make it a separate PR for adding the prettier config and running prettier if that is preferred.

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
